services:
  - type: web
    name: plateforme-projets
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestion_projets

